
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-05
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1MDkyNjE2","is_bot":false,"login":"jiwa310","name":"Jim Wang"},"headRefName":"jiwa310-GESearchPage","number":37,"title":"jiwa310 - Implemented GE Search Page","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/37"},{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"vs-Course-Details-Bug","number":36,"title":"Modified title field for SectionsTable to link to details page","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/36"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-personal-schedule-weekly-view","number":35,"title":"Weekly View for Personal Schedules","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/35"},{"author":{"id":"MDQ6VXNlcjY3NzI0NTIw","is_bot":false,"login":"austish","name":"Austin Quach"},"headRefName":"aq-GEAreaSearchForm","number":34,"title":"GE Area Search Form Component","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/34"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-paginate-frontend","number":32,"title":"FEATURE: Paginate the Job Log Table","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/32"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-austish-GESearchPage","number":30,"title":"Pc austish ge search page","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/30"},{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"vs-Classrooms-for-Building","number":29,"title":"Added a new endpoint for searching by building code and room number","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/29"},{"author":{"id":"MDQ6VXNlcjY1MDkyNjE2","is_bot":false,"login":"jiwa310","name":"Jim Wang"},"headRefName":"jiwa310-GE-list-API","number":26,"title":"GE List API","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-05/pull/26"}]
